---
title: "CodeBook.md"
author: "bjw2119"
date: "August 22, 2015"
output: html_document
---
This Code Book describes the processes used by the R script "run_analysis.R" to clean and aggregate the means and standard deviations of acceleration, magnitude, and Fast-Fourier transformed data collected from Samsung smartphones' acclerometers and gyroscopes worn by 30 subjects performing Activities of Daily Living in the study: Davide Anguita, Alessandro Ghio, Luca Oneto, Xavier Parra and Jorge L. Reyes-Ortiz. Human Activity Recognition on Smartphones using a Multiclass Hardware-Friendly Support Vector Machine. International Workshop of Ambient Assisted Living (IWAAL 2012). Vitoria-Gasteiz, Spain. Dec 2012. Documentation for the study's variables found in the "features_info.txt" file was used in the constructino of this Code Book.
##Untidy Data Format and Layout

The *Anguita et al* data file is split into two categories, one for training and the other for testing, with observations of 21 and 9 subjects each, respectively. Both the testing and training group each have three data files in the .txt format: a table of observations of 561 vector measures relating to acceleration along the x,y, and z axes; an index listing the subject ID number associated with the aforementioned observations; and an index listing th ADL activity taking place during the observation, as coded by hand by observers reviewing videotapes of the study.

##Script

###Test and Training Set Assembly

The run_analysis.R script begins by loading 3 data files in a .txt format each from both the test group folder and the training group folder using

*read.table(file_path)*

An additional file, "features.txt" containing the labels of the acceleration variable measurements is also read in as a table.

The variables are appended to their respective columns using the names() function to assign the labels to the observation table columns after converting the labels to factor variables using as.factor().

The activity and subject ID dimensions are then simply appended to the data frames as new columns using the df$column = vector assignment method, after which they are moved to the front (left) of the dataset to make it easier for readers to orient themselves by the subject ID and activity dimensions.

The now-complete test and training set data frames are bound together using rbind to create the fullSet data frame.

###Filtering and Aggregation

Two logical vectors are created using the grepl() function to identify column variables with "mean" and "std" measurements (including mean frequency variables from Fast Fourier Transformations) created by *Anguita et al*. These vectors are then used with [] to extract the columns from fullSet to be placed into the trimmedSet variable, after which the activity and subject ID dimension columns are appended, moved to the front, and the column labels re-attached.

The aggregation() function is then run by subject ID and activity to create means of the selected mean and std columns in the trimmedSet. The resulting aggregated set is stored in the variable aggdata.

The column labels are updated to reflect that they are the means of the original study's vector fields using the paste() function. (See "Variables" below).

###Output
The resulting tidy data set is written to a .txt file with no row names, run_analysis_tidy_output.txt, using write.table(). The output can also easily be written to a .csv file for ease of viewing.


##Variables
The variables included in this output are the means of 79 means and standard deviations of measures included in the original *Anguita et al* data set, as well as the two dimenional variables, subject ID and activity. There are 26 original types of measurements taken, including 19 measurements and statistics on accerlation along the X, Y, and Z axes (for a total of 57). Also included are the mean and standard deviation of the following: body, gyroscope, and gravity acceleration magnitude; and body and gyroscopte acceleration jerk magnitude (for a total of 10). Finally, mean, standard deviation, and mean frequency of the Fast Fourier transformation of body acceleration magnitude, body acceleration jerk magnitude, body gyroscopic acceleration magnitude, and body gyroscopic accleration jerk magnitude are also included (for a total of 12). These 79 (57+10+12), in addition to the activity and subject ID dimensions (2) result in the following 81 variables (the 79 non-dimensional variables are the means of the data from *Anguita et al*:

1. subjID
2. activity
3. mean.of.tBodyAcc-mean()-X
4. mean.of.tBodyAcc-mean()-Y
5. mean.of.tBodyAcc-mean()-Z
6. mean.of.tBodyAcc-std()-X
7. mean.of.tBodyAcc-std()-Y
8. mean.of.tBodyAcc-std()-Z
9. mean.of.tGravityAcc-mean()-X
10. mean.of.tGravityAcc-mean()-Y
11. mean.of.tGravityAcc-mean()-Z
12. mean.of.tGravityAcc-std()-X
13. mean.of.tGravityAcc-std()-Y
14. mean.of.tGravityAcc-std()-Z
15. mean.of.tBodyAccJerk-mean()-X
16. mean.of.tBodyAccJerk-mean()-Y
17. mean.of.tBodyAccJerk-mean()-Z
18. mean.of.tBodyAccJerk-std()-X
19. mean.of.tBodyAccJerk-std()-Y
20. mean.of.tBodyAccJerk-std()-Z
21. mean.of.tBodyGyro-mean()-X
22. mean.of.tBodyGyro-mean()-Y
23. mean.of.tBodyGyro-mean()-Z
24. mean.of.tBodyGyro-std()-X
25. mean.of.tBodyGyro-std()-Y
26. mean.of.tBodyGyro-std()-Z
27. mean.of.tBodyGyroJerk-mean()-X
28. mean.of.tBodyGyroJerk-mean()-Y
29. mean.of.tBodyGyroJerk-mean()-Z
30. mean.of.tBodyGyroJerk-std()-X
31. mean.of.tBodyGyroJerk-std()-Y
32. mean.of.tBodyGyroJerk-std()-Z
33. mean.of.tBodyAccMag-mean()
34. mean.of.tBodyAccMag-std()
35. mean.of.tGravityAccMag-mean()
36. mean.of.tGravityAccMag-std()
37. mean.of.tBodyAccJerkMag-mean()
38. mean.of.tBodyAccJerkMag-std()
39. mean.of.tBodyGyroMag-mean()
40. mean.of.tBodyGyroMag-std()
41. mean.of.tBodyGyroJerkMag-mean()
42. mean.of.tBodyGyroJerkMag-std()
43. mean.of.fBodyAcc-mean()-X
44. mean.of.fBodyAcc-mean()-Y
45. mean.of.fBodyAcc-mean()-Z
46. mean.of.fBodyAcc-std()-X
47. mean.of.fBodyAcc-std()-Y
48. mean.of.fBodyAcc-std()-Z
49. mean.of.fBodyAcc-meanFreq()-X
50. mean.of.fBodyAcc-meanFreq()-Y
51. mean.of.fBodyAcc-meanFreq()-Z
52. mean.of.fBodyAccJerk-mean()-X
53. mean.of.fBodyAccJerk-mean()-Y
54. mean.of.fBodyAccJerk-mean()-Z
55. mean.of.fBodyAccJerk-std()-X
56. mean.of.fBodyAccJerk-std()-Y
57. mean.of.fBodyAccJerk-std()-Z
58. mean.of.fBodyAccJerk-meanFreq()-X
59. mean.of.fBodyAccJerk-meanFreq()-Y
60. mean.of.fBodyAccJerk-meanFreq()-Z
61. mean.of.fBodyGyro-mean()-X
62. mean.of.fBodyGyro-mean()-Y
63. mean.of.fBodyGyro-mean()-Z
64. mean.of.fBodyGyro-std()-X
65. mean.of.fBodyGyro-std()-Y
66. mean.of.fBodyGyro-std()-Z
67. mean.of.fBodyGyro-meanFreq()-X
68. mean.of.fBodyGyro-meanFreq()-Y
69. mean.of.fBodyGyro-meanFreq()-Z
70. mean.of.fBodyAccMag-mean()
71. mean.of.fBodyAccMag-std()
72. mean.of.fBodyAccMag-meanFreq()
73. mean.of.fBodyBodyAccJerkMag-mean()
74. mean.of.fBodyBodyAccJerkMag-std()
75. mean.of.fBodyBodyAccJerkMag-meanFreq()
76. mean.of.fBodyBodyGyroMag-mean()
77. mean.of.fBodyBodyGyroMag-std()
78. mean.of.fBodyBodyGyroMag-meanFreq()
79. mean.of.fBodyBodyGyroJerkMag-mean()
80. mean.of.fBodyBodyGyroJerkMag-std()
81. mean.of.fBodyBodyGyroJerkMag-meanFreq()


